[workspace]
members = [
  "crates/lair_keystore",
  "crates/lair_keystore_api",
  "crates/lair_keystore_client",
]

[patch.crates-io]
ghost_actor = { git = "https://github.com/holochain/ghost_actor.git", branch = "add_observability" }