[package]
name = "hc_seed_bundle"
version = "0.1.3"
description = "SeedBundle parsing and generation library."
license = "MIT OR Apache-2.0"
repository = "https://github.com/holochain/lair"
documentation = "https://docs.rs/hc_seed_bundle"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
keywords = [ "holochain", "holo", "keystore", "secret", "cryptography" ]
categories = [ "cryptography" ]
edition = "2018"

[dependencies]
futures = "0.3.24"
one_err = "0.0.6"
rmp-serde = "1.1.0"
rmpv = { version = "1.0.0", features = [ "with-serde" ] }
serde = { version = "1", features = [ "derive", "rc" ] }
serde_bytes = "0.11.7"
sodoken = "=0.0.5"

[dev-dependencies]
base64 = "0.13"
serde_json = "1"
tokio = { version = "1.20.1", features = [ "full" ] }
