[package]
name = "lair_keystore"
version = "0.2.1"
resolver = "2"
description = "secret lair private keystore"
license = "MIT OR Apache-2.0"
repository = "https://github.com/holochain/lair"
documentation = "https://docs.rs/lair_keystore"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
keywords = [ "holochain", "holo", "keystore", "secret", "cryptography" ]
categories = [ "cryptography" ]
edition = "2018"

[dependencies]
# lair_keystore_api must be pinned to enable strict version checks
lair_keystore_api = { version = "=0.2.1", path = "../lair_keystore_api" }
rpassword = "7.0.0"
structopt = "0.3.26"
sysinfo = "0.26.1"
tracing-subscriber = { version = "0.3.15", features = [ "env-filter" ] }

# switch to bundled-sqlcipher-vendored-openssl once this is released:
# https://github.com/rusqlite/rusqlite/issues/966
# also can remove `resolver = "2"` when this is no longer different by os
[target.'cfg(windows)'.dependencies]
rusqlite = { version = "0.28", features = [ "bundled" ] }

# remove `resolver = "2"` when this is no longer different by os
[target.'cfg(not(windows))'.dependencies]
rusqlite = { version = "0.28", features = [ "bundled-sqlcipher-vendored-openssl" ] }

[build-dependencies]
lair_keystore_api = { version = "0.2.1", path = "../lair_keystore_api" }
pretty_assertions = "1.3.0"
sqlformat = "0.2.0"

[dev-dependencies]
criterion = "0.3.6"
tempdir = "0.3.7"

[lib]
name = "lair_keystore"
path = "src/lib.rs"

[[bin]]
name = "lair-keystore"
path = "src/bin/lair-keystore-bin/main.rs"
