[package]
name = "lair_keystore"
version = "0.0.1-alpha.7"
description = "secret lair private keystore"
license = "Apache-2.0"
repository = "https://github.com/holochain/lair"
documentation = "https://docs.rs/lair_keystore"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
keywords = [ "holochain", "holo", "keystore", "secret", "cryptography" ]
categories = [ "cryptography" ]
edition = "2018"

[dependencies]
futures = "0.3"
ghost_actor = "0.3.0-alpha.1"
lair_keystore_api = { version = "=0.0.1-alpha.7", path = "../lair_keystore_api" }
structopt = "0.3"
sysinfo = "0.15"
thiserror = "1"
tokio = { version = "0.2", features = [ "full" ] }
tracing = "0.1"
tracing-subscriber = "0.2"

[build-dependencies]
lair_keystore_api = { version = "=0.0.1-alpha.7", path = "../lair_keystore_api" }

[dev-dependencies]
criterion = "0.3"
once_cell = "1.4"
tempfile = "3"

[lib]
name = "lair_keystore"
path = "src/lib.rs"

[[bin]]
name = "lair-keystore"
path = "src/bin/lair-keystore/main.rs"

[[bench]]
name = "signature_generation"
harness = false
