[package]
name = "lair_keystore_api"
version = "0.1.0"
description = "secret lair private keystore API library"
license = "Apache-2.0"
repository = "https://github.com/holochain/lair"
documentation = "https://docs.rs/lair_keystore_api"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
keywords = [ "holochain", "holo", "keystore", "secret", "cryptography" ]
categories = [ "cryptography" ]
edition = "2018"

[dependencies]
base64 = "0.13.0"
dunce = "1.0.2"
hc_seed_bundle = { version = "=0.1.0", path = "../hc_seed_bundle" }
lru = "0.6.6"
nanoid = "0.4.0"
once_cell = "1.8.0"
parking_lot = "0.11.2"
rcgen = "0.8.13"
serde = { version = "1", features = [ "derive", "rc" ] }
serde_json = "1.0.68"
serde_yaml = "0.8.21"
tokio = { version = "1.12.0", features = [ "full" ] }
toml = "0.5.8"
tracing = "0.1.28"
url = { version = "2.2.2", features = [ "serde" ] }

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"

[dev-dependencies]
assert_cmd = "2.0.1"
tempdir = "0.3.7"
tracing-subscriber = "0.2.24"

[build-dependencies]
toml = "0.5.8"
