[package]
name = "lair_keystore_api"
version = "0.0.1-alpha.12"
description = "secret lair private keystore types"
license = "Apache-2.0"
repository = "https://github.com/holochain/lair"
documentation = "https://docs.rs/lair_keystore_api"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
keywords = [ "holochain", "holo", "keystore", "secret", "cryptography" ]
categories = [ "cryptography" ]
edition = "2018"

[dependencies]
blake2b_simd = "0.5.10"
byteorder = "1"
derive_more = "0.99"
directories = "3"
futures = "0.3"
ghost_actor = "0.3.0-alpha.1"
nanoid = "0.3"
num_cpus = "1"
once_cell = "1.4"
rayon = "1.3"
rcgen = "0.8.5"
ring = "0.16"
thiserror = "1"
tokio = { version = "1.7.1", features = [ "full" ] }
toml = "0.5"
rand = "0.7"
crypto_box = "0.5"
subtle = "2.3"
block-padding = "0.2.1"

[dev-dependencies]
tempfile = "3"
tracing-subscriber = "0.2"

[build-dependencies]
toml = "0.5"
