[package]
name = "lair_keystore_api"
version = "0.1.0-alpha.1"
description = "secret lair private keystore types"
license = "Apache-2.0"
repository = "https://github.com/holochain/lair"
documentation = "https://docs.rs/lair_keystore_api"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
keywords = [ "holochain", "holo", "keystore", "secret", "cryptography" ]
categories = [ "cryptography" ]
edition = "2018"

[dependencies]
futures = "0.3.17"
nanoid = "0.4.0"
one_err = "0.0.4"
once_cell = "1.8.0"
parking_lot = "0.11.2"
rcgen = "0.8.13"
sodoken = "=0.0.1-alpha.18"
tokio = { version = "1.11.0", features = [ "full" ] }
toml = "0.5.8"
tracing = "0.1.28"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"

[dev-dependencies]
tracing-subscriber = "0.2.24"

[build-dependencies]
toml = "0.5.8"
