[package]
name = "lair_keystore_api"
version = "0.2.1"
description = "secret lair private keystore API library"
license = "MIT OR Apache-2.0"
repository = "https://github.com/holochain/lair"
documentation = "https://docs.rs/lair_keystore_api"
authors = [ "Holochain Core Dev Team <devcore@holochain.org>" ]
keywords = [ "holochain", "holo", "keystore", "secret", "cryptography" ]
categories = [ "cryptography" ]
edition = "2018"

[dependencies]
base64 = "0.13.0"
dunce = "1.0.2"
# this doesn't strictly need to be pinned, but it supports the
# determinism of the strict client/server version checks
hc_seed_bundle = { version = "=0.1.3", path = "../hc_seed_bundle" }
lru = "0.7.8"
nanoid = "0.4.0"
once_cell = "1.13.1"
parking_lot = "0.12.1"
rcgen = { version = "0.9.3", features = [ "zeroize" ] }
serde = { version = "1", features = [ "derive", "rc" ] }
serde_json = "1"
serde_yaml = "0.9.10"
tokio = { version = "1.20.1", features = [ "full" ] }
toml = "0.5.9"
tracing = "0.1.36"
url = { version = "2.2.2", features = [ "serde" ] }
zeroize = "1.5.7"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"

[dev-dependencies]
assert_cmd = "2.0.4"
tempdir = "0.3.7"
tracing-subscriber = { version = "0.3.15", features = [ "env-filter" ] }

[build-dependencies]
toml = "0.5.8"
