name: static analysis

on: [ push ]

jobs:

 static-analysis:
  runs-on: ${{ matrix.os }}
  strategy:
   matrix:
    os: [
     ubuntu-latest,
    ]
    toolchain: [
     stable,
    ]
  steps:
   - uses: actions/checkout@v2

   - name: linux-sqlcipher
     if: ${{ runner.os == 'Linux' }}
     run: sudo apt-get install sqlcipher-dev

#   - name: rust cache
#     uses: actions/cache@v2
#     env:
#      cache-name: cache-rust-static
#     with:
#      path: |
#        ~/.cargo/registry
#        ~/.cargo/git
#        target
#      key: ${{ runner.os }}-cargo-${{ env.cache-name }}-${{ matrix.toolchain }}-${{ hashFiles('Cargo.toml') }}-${{ hashFiles('crates/**/Cargo.toml') }}
#      restore-keys: |
#       ${{ runner.os }}-cargo-${{ env.cache-name }}-${{ matrix.toolchain }}-

   - uses: actions-rs/toolchain@v1
     with:
      toolchain: ${{ matrix.toolchain }}
      components: rustfmt, clippy

   - uses: actions-rs/cargo@v1
     with:
      command: fmt
      args: -- --check

   - uses: actions-rs/cargo@v1
     with:
      command: clippy
